node("docker") {
    docker.withRegistry('https://registry.hub.docker.com','docker-hub-id') {
    
        git url: "https://github.com/kaashyapa32/test-jk.git", credentialsId: 'kaashyapa32'
    
        sh "git rev-parse HEAD > .git/commit-id"
        def commit_id = readFile('.git/commit-id').trim()
        println commit_id
    
        stage "build"
        def app = docker.build "demoapp2"
    
        stage "publish"
        app.push 'master'
        app.push "${commit_id}"
    }
}