FROM ubuntu

EXPOSE 8092
VOLUME /tmp
ADD /target/jenkins-github-0.0.1-SNAPSHOT.jar myapp.jar
RUN sh -c 'touch /myapp.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/myapp.jar"]